apiVersion: v1
data:
  DRUID_LOG4J: <?xml version="1.0" encoding="UTF-8" ?><Configuration status="WARN"><Appenders><Console
    name="Console" target="SYSTEM_OUT"><PatternLayout pattern="%d{ISO8601} %p [%t]
    %c - %m%n"/></Console></Appenders><Loggers><Root level="info"><AppenderRef ref="Console"/></Root><Logger
    name="org.apache.druid.jetty.RequestLog" additivity="false" level="DEBUG"><AppenderRef
    ref="Console"/></Logger></Loggers></Configuration>
  DRUID_MAXDIRECTMEMORYSIZE: 6172m
  DRUID_MAXNEWSIZE: 250m
  DRUID_NEWSIZE: 250m
  DRUID_XMS: 1g
  DRUID_XMX: 1g
  druid_coordinator_balancer_strategy: cachingCost
  druid_emitter_logging_logLevel: debug
  druid_extensions_loadList: '["druid-histogram", "druid-datasketches", "druid-lookups-cached-global",
    "postgresql-metadata-storage", "druid-hdfs-storage", "druid-kafka-indexing-service",
    "druid-avro-extensions"]'
  druid_indexer_fork_property_druid_processing_buffer_sizeBytes: "268435456"
  druid_indexer_logs_directory: /opt/data/indexing-logs
  druid_indexer_logs_type: file
  druid_indexer_runner_javaOptsArray: '["-server", "-Xmx1g", "-Xms1g", "-XX:MaxDirectMemorySize=3g",
    "-Duser.timezone=UTC", "-Dfile.encoding=UTF-8", "-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"]'
  druid_metadata_storage_connector_connectURI: jdbc:postgresql://postgres:5432/druid
  druid_metadata_storage_connector_password: FoolishPassword
  druid_metadata_storage_connector_user: druid
  druid_metadata_storage_host: ""
  druid_metadata_storage_type: postgresql
  druid_processing_numMergeBuffers: "2"
  druid_processing_numThreads: "2"
  druid_storage_storageDirectory: /opt/data/segments
  druid_storage_type: local
  druid_zk_service_host: zookeeper
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: middlemanager-environment
  name: middlemanager-environment
