apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: divolte
  name: divolte
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: divolte
    spec:
      containers:
      - env:
        - name: DIVOLTE_KAFKA_BROKER_LIST
          value: kafka:29092
        image: divolte/divolte-collector
        name: divolte
        ports:
        - containerPort: 8290
        resources: {}
        volumeMounts:
        - mountPath: /opt/divolte/divolte-collector/conf/
          name: divolte-claim0
      restartPolicy: Always
      volumes:
      - name: divolte-claim0
        persistentVolumeClaim:
          claimName: divolte-claim0
status: {}
