apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: divolte
  name: divolte
spec:
  ports:
  - name: "8290"
    port: 8290
    targetPort: 8290
  selector:
    io.kompose.service: divolte
status:
  loadBalancer: {}
